apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels:
    env: monitor
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: laxmanch341/prometheus:v521
      ports:
        - containerPort: 9090
          name: "prom-server"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
